spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
#          max-completion-tokens: 200
    chat:
      client:
        enabled: false
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: codellama:latest
          temperature: 0.5