spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
    chat:
      client:
        enabled: false
    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  datasource:
    url: jdbc:postgresql://localhost:5432/springAi
    username: myuser
    password: mypassword

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG